### ISSUE TITLE
坑点提问

### ISSUE THREAD

**Issue by shuiyihang** [junxi-haoyi/Aniya#1]
我看你是换了34引脚的屏，只要配置成原来的通讯方式，不应该就可以了吗，为什么搞这么久哇哈哈

**Comment by junxi-haoyi** [comment]
最近在偷懒，找到工作了，放了个小假，sorry🐔🐔🐔

**Comment by junxi-haoyi** [comment]
还有ESP-IDF的开发方式，文档的阅读，LovyanGFX不支持QSPI需要手动添加，还有UI动画什么的，而且这个项目目前还没有做完，目前来看就是一个玩具而已

**Comment by junxi-haoyi** [comment]
还有3D建模也是新学的，反正这个项目也是模仿大佬的，自己在这个过程中学会很多
